# Generated by Django 5.2.4 on 2025-08-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('video', models.FileField(blank=True, null=True, upload_to='announcements/videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='announcements/audios/')),
            ],
        ),
    ]
