# Generated by Django 5.2.4 on 2025-08-27 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_picture',
            field=models.ImageField(blank=True, null=True, upload_to='parents/images'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/images'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 13, 5, 30, 9141, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 13, 5, 30, 9194, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='relation_ship',
            field=models.CharField(choices=[('አባት', 'አባት'), ('እናት', 'እናት'), ('አሳዳጊ', 'አሳዳጊ'), ('ሌላ', 'ሌላ')]),
        ),
    ]
