# Generated by Django 5.2.4 on 2025-08-27 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_parent_parent_picture_student_student_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 21, 42, 25, 418787, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 21, 42, 25, 418833, tzinfo=datetime.timezone.utc)),
        ),
    ]
