# Generated by Django 5.2.4 on 2025-08-17 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_student_age_alter_student_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registered_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2013, 8, 20, 7, 54, 42, 812450, tzinfo=datetime.timezone.utc)),
        ),
    ]
