# Generated by Django 5.2.4 on 2025-08-22 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_academicyear_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2010, 8, 26, 9, 47, 21, 383850, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 9, 47, 21, 333857, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 9, 47, 21, 333911, tzinfo=datetime.timezone.utc)),
        ),
    ]
