# Generated by Django 5.2.4 on 2025-09-05 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_autosectiongrade_grade_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 6, 32, 52, 969178, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 6, 32, 52, 969229, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autosectiongrade',
            name='grade',
            field=models.CharField(choices=[('grade 9', 'Grade 9'), ('grade 10', 'Grade 10'), ('grade 11', 'Grade 11'), ('grade 12', 'Grade 12')], default='grade 9', max_length=20),
            preserve_default=False,
        ),
    ]
