# Generated by Django 5.2.4 on 2025-08-17 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_remove_student_registered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2013, 8, 20, 7, 59, 42, 292839, tzinfo=datetime.timezone.utc)),
        ),
    ]
