# Generated by Django 5.2.4 on 2025-09-05 16:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGradeStat',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('stats', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 16, 53, 32, 784872, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 16, 53, 32, 784959, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='autosectiongrade',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.autogradestat'),
        ),
    ]
