# Generated by Django 5.2.4 on 2025-09-05 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_autogradestat_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 17, 6, 6, 999914, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 17, 6, 6, 999960, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autogradestat',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
