# Generated by Django 5.2.4 on 2025-08-22 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_student_parent_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='grand_father_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 9, 58, 52, 671172, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 9, 58, 52, 671225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2010, 8, 26, 9, 58, 52, 720310, tzinfo=datetime.timezone.utc)),
        ),
    ]
