# Generated by Django 5.2.4 on 2025-08-17 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_alter_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(choices=[('grade 9', 'fresh(9)'), ('grade 10', 'sophomore(10)'), ('grade 11', 'junior(11)'), ('grade 12', 'senior(12)')], default='grade 9', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2013, 8, 20, 8, 3, 26, 613842, tzinfo=datetime.timezone.utc)),
        ),
    ]
