# Generated by Django 5.2.4 on 2025-08-30 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='autosectiongrade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='autosectiongrade',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 30, 6, 7, 55, 314432, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 30, 6, 7, 55, 314490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='autosectiongrade',
            constraint=models.UniqueConstraint(fields=('student_name', 'father_name', 'grandfather_name'), name='unique_student_fullname'),
        ),
    ]
