# Generated by Django 5.2.4 on 2025-09-06 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autosectiongrade',
            name='minstry_score',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 6, 8, 21, 35, 625650, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 6, 8, 21, 35, 625698, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autosectiongrade',
            name='previous_school',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
