# Generated by Django 5.2.4 on 2025-08-22 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_rename_last_name_student_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentform',
            name='relation_ship',
            field=models.CharField(choices=[('አባት', 'አባት'), ('እናት', 'እናት'), ('አሳዳጊ', 'አሳዳጊ'), ('ሌላ', 'ሌላ')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 10, 11, 15, 688439, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 10, 11, 15, 688487, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2010, 8, 26, 10, 11, 15, 761476, tzinfo=datetime.timezone.utc)),
        ),
    ]
