# Generated by Django 5.2.4 on 2025-08-30 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_alter_autosectiongrade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosectiongrade',
            name='sex',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 30, 6, 10, 0, 403694, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 30, 6, 10, 0, 403782, tzinfo=datetime.timezone.utc)),
        ),
    ]
