# Generated by Django 5.2.4 on 2025-08-31 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_autosectiongrade_sex_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoSectionGrade',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 31, 6, 55, 33, 525851, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 31, 6, 55, 33, 525901, tzinfo=datetime.timezone.utc)),
        ),
    ]
