# Generated by Django 5.2.4 on 2025-08-22 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_parentform_relation_ship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 10, 15, 55, 471562, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 10, 15, 55, 471618, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2010, 8, 26, 10, 15, 55, 524267, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
