# Generated by Django 5.2.4 on 2025-08-17 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_alter_academicyear_end_date_alter_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2013, 8, 20, 8, 7, 42, 866741, tzinfo=datetime.timezone.utc)),
        ),
    ]
