# Generated by Django 5.2.4 on 2025-09-12 16:37

import announcement.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_remove_autosectiongrade_minstry_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='announcements/audios/', validators=[announcement.models.validate_file_size, announcement.models.validate_audio_type]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images/', validators=[announcement.models.validate_file_size, announcement.models.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='announcements/videos/', validators=[announcement.models.validate_file_size, announcement.models.validate_video_type]),
        ),
    ]
