# Generated by Django 5.2.4 on 2025-08-22 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentForm',
            new_name='Parent',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 10, 50, 30, 919933, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 10, 50, 30, 919983, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2010, 8, 26, 10, 50, 30, 970320, tzinfo=datetime.timezone.utc)),
        ),
    ]
