# Generated by Django 5.2.4 on 2025-08-23 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0011_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicyear',
            old_name='end_date',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='academicyear',
            old_name='start_date',
            new_name='start_year',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 5, 47, 50, 994620, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 5, 47, 50, 994690, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2010, 8, 27, 5, 47, 51, 103052, tzinfo=datetime.timezone.utc)),
        ),
    ]
