# Generated by Django 5.2.4 on 2025-08-17 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0011_alter_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2013, 8, 20, 8, 12, 31, 846868, tzinfo=datetime.timezone.utc)),
        ),
    ]
