# Generated by Django 5.2.4 on 2025-08-23 14:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0012_rename_end_date_academicyear_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 14, 39, 7, 480854, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 14, 39, 7, 480907, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grade',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='announcement.academicyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2010, 8, 27, 14, 39, 7, 531452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('ወንድ', 'ወንድ'), ('ሰት', 'ሰት')], max_length=10),
        ),
    ]
