# Generated by Django 5.2.4 on 2025-08-24 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0013_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 6, 33, 37, 765687, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 6, 33, 37, 765809, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2010, 8, 28, 6, 33, 37, 825349, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('name', 'academic_year')},
        ),
    ]
