# Generated by Django 5.2.4 on 2025-08-17 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0013_alter_student_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kebele',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2013, 8, 20, 8, 15, 14, 479644, tzinfo=datetime.timezone.utc)),
        ),
    ]
