# Generated by Django 5.2.4 on 2025-08-17 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0014_student_kebele_alter_student_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='student_name',
        ),
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grand_father_name',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='past_school_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2013, 8, 20, 17, 28, 29, 766990, tzinfo=datetime.timezone.utc)),
        ),
    ]
