# Generated by Django 5.2.4 on 2025-08-24 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0014_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 6, 38, 5, 946070, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 6, 38, 5, 946120, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2010, 8, 28, 6, 38, 6, 1372, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_name', 'father_name', 'grand_father_name', 'section')},
        ),
    ]
