# Generated by Django 5.2.4 on 2025-08-25 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0015_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 25, 6, 18, 41, 408115, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 25, 6, 18, 41, 408161, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2010, 8, 29, 6, 18, 41, 460748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('name', 'father_name')},
        ),
    ]
