# Generated by Django 5.2.4 on 2025-09-01 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0016_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 6, 15, 9, 433841, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 6, 15, 9, 433919, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='autosectiongrade',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
